# Generated by Django 3.2.4 on 2021-06-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('error_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500)),
                ('location', models.CharField(choices=[('K', 'Konfektion'), ('DuO', 'Druckwerke und Oberflaechenbeschichtung'), ('V', 'Vorbehandlung'), ('LEE', 'Laser-Edge-Extruder'), ('KmA', 'Kuehlstrecke mit Abzug'), ('E', 'Extruder')], max_length=3)),
                ('error_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorcategory')),
            ],
        ),
    ]
