# Generated by Django 3.2.6 on 2021-08-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0002_alter_solution_error_appearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorappearance',
            options={'verbose_name': 'Erscheinungsbild', 'verbose_name_plural': 'Erscheiungsbilder'},
        ),
    ]
