# Generated by Django 3.2.6 on 2021-08-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0003_alter_errorappearance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'verbose_name': 'Fehlerkategorie', 'verbose_name_plural': 'Fehlerkategorien'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Lösung', 'verbose_name_plural': 'Lösungen'},
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='description',
            field=models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='error_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorcategory', verbose_name='Fehlerkategorie'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='location',
            field=models.CharField(choices=[('K', 'Konfektion'), ('DuO', 'Druckwerke und Oberflaechenbeschichtung'), ('V', 'Vorbehandlung'), ('LEE', 'Laser-Edge-Extruder'), ('KmA', 'Kuehlstrecke mit Abzug'), ('E', 'Extruder')], max_length=3, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='description',
            field=models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='error_appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
