# Generated by Django 3.2.6 on 2021-09-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0005_auto_20210911_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=5000, verbose_name='Inhalt')),
                ('type', models.CharField(choices=[('A', 'Neuer Lösungsvorschlag'), ('B', 'Kommentar zu bestehender Lösung')], max_length=1, verbose_name='Typ')),
                ('error_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.solution', verbose_name='Lösung')),
            ],
        ),
    ]
