# Generated by Django 3.2.6 on 2021-09-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_site', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='error_appearance',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='solution',
        ),
        migrations.AddField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(models.Q(('app_label', 'user_site'), ('model', 'error_appearance')), models.Q(('app_label', 'user_site'), ('model', 'solution')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content page'),
        ),
        migrations.AddField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(default=None, verbose_name='related object'),
        ),
    ]
