# Generated by Django 3.2.6 on 2021-09-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_site', '0007_auto_20210911_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='type',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('model', 'error_appearance'), ('model', 'solution'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Zugehörigkeit'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(default=None, verbose_name='Zugehöriges Objekt'),
        ),
    ]
