# Generated by Django 3.2.6 on 2021-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0011_auto_20210912_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='error_appearance',
            field=models.CharField(default=None, max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='error_category',
            field=models.CharField(default=None, max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='solution',
            field=models.CharField(default=None, max_length=200, verbose_name='Name'),
        ),
    ]
