# Generated by Django 3.2.6 on 2021-09-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0015_alter_overview_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='overview',
            table='overview',
        ),
    ]
