# Generated by Django 3.2.6 on 2021-09-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0018_alter_overview_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name': 'Übersicht', 'verbose_name_plural': 'Übersicht'},
        ),
    ]
