# Generated by Django 3.2.6 on 2021-09-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0021_alter_overview_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='error_appearance',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='solution',
        ),
        migrations.AddField(
            model_name='overview',
            name='name',
            field=models.CharField(default='', max_length=5000, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='error_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='user_site.errorcategory', verbose_name='Fehlerkategorie'),
        ),
    ]
