# Generated by Django 3.2.6 on 2021-09-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0023_auto_20210912_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overview',
            options={'managed': False, 'verbose_name': 'Übersicht', 'verbose_name_plural': 'Übersicht'},
        ),
    ]
