# Generated by Django 3.2.6 on 2021-09-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0024_alter_overview_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='overview',
            table='user_site_overview',
        ),
    ]
