# Generated by Django 3.2.6 on 2021-09-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0027_auto_20210912_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(default='Keine spezifische Beschreibung vorhanden', max_length=500, verbose_name='Beschreibung')),
            ],
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.location', verbose_name='Fehlerort'),
        ),
    ]
