# Generated by Django 3.2.6 on 2021-09-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0028_auto_20210919_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Fehlerort', 'verbose_name_plural': 'Fehlerorte'},
        ),
        migrations.AddField(
            model_name='location',
            name='pdf_document',
            field=models.FileField(default='', upload_to='locations/', verbose_name='PDF Dokument'),
        ),
    ]
