# Generated by Django 3.2.6 on 2021-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0030_auto_20210919_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorappearance',
            name='media',
            field=models.FileField(default='error_appearances/coming_soon.png', upload_to='error_appearances/', verbose_name='Bild/Video'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='media',
            field=models.FileField(default='solutions/coming_soon.png', upload_to='solutions/', verbose_name='Bild/Video'),
        ),
    ]
