# Generated by Django 3.2.6 on 2021-09-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_site', '0026_auto_20210912_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=5000, verbose_name='Inhalt')),
                ('solution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.solution', verbose_name='Lösung')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nlp_component.comment')),
                ('error_appearance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
            ],
            options={
                'verbose_name': 'Neuer Lösungsvorschlag',
                'verbose_name_plural': 'Neue Lösungsvorschläge',
            },
            bases=('nlp_component.comment', models.Model),
        ),
        migrations.CreateModel(
            name='EditComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nlp_component.comment')),
                ('error_appearance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
            ],
            options={
                'verbose_name': 'Lösungskommentar',
                'verbose_name_plural': 'Lösungskommentare',
            },
            bases=('nlp_component.comment', models.Model),
        ),
    ]
