# Generated by Django 3.2.6 on 2021-09-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0027_auto_20210912_2118'),
        ('nlp_component', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='editcomment',
            name='error_appearance',
        ),
        migrations.AddField(
            model_name='editcomment',
            name='solution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.solution', verbose_name='Lösung'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=5000, verbose_name='Inhalt'),
        ),
    ]
