# Generated by Django 3.2.6 on 2021-09-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0028_auto_20210919_1353'),
        ('nlp_component', '0002_auto_20210912_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editcomment',
            options={'verbose_name': 'Überarbeiteter Lösungsvorschlag', 'verbose_name_plural': 'Überarbeitete Lösungsvorschläge'},
        ),
        migrations.AlterField(
            model_name='requestcomment',
            name='error_appearance',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild'),
        ),
    ]
